### ISSUE TITLE
Generating HTML in .til dir

### ISSUE THREAD

**Issue by sdthaker** [omalk98/TILvert#1]
When we don't pass an output directory, it generates til directory and stores the HTML files into that dir. However, it replicates the existing dir structure at the root level, in a way that it creates empty folders for which it didn't find .txt files but those directories had files ending in different extensions other than .txt.

**Comment by sdthaker** [comment]
The issue was fixed in latest commit.

**Comment by omalk98** [comment]
Fix Commit #[b64c017](https://github.com/omalk98/TILvert/commit/b64c017d830c13e1a6ed306d4babb6938992ac9e)
