### ISSUE TITLE
Error handling when file or directory doesn't exist

### ISSUE THREAD

**Issue by sdthaker** [omalk98/TILvert#2]
Proper error handling will be nice to have when we pass a directory or file which doesn't exist. 

Just a suggestion: A one-liner error message that instructs the user what happened and what was expected of them, would be a good way to instruct them may be.

![image](https://github.com/omalk98/TILvert/assets/71615163/9b797fd8-bcbf-4180-a28f-9c2186509579)

![image](https://github.com/omalk98/TILvert/assets/71615163/f06bb49a-df6e-4b1d-9b58-649940ac3a0a)

**Comment by omalk98** [comment]
Fixed with commit #[c065866](https://github.com/omalk98/TILvert/commit/c065866c8a1e5324092d266ed0c89bff85890176)
