### ISSUE TITLE
Deleting til directory manually to generate files to it

### ISSUE THREAD

**Issue by sdthaker** [omalk98/TILvert#4]
After deleting til dir manually, and then passing it a text file that is stored at the root level, we get this error. 

A possibility you might have to check and make the dir if doesn't exist already.

![image](https://github.com/omalk98/TILvert/assets/71615163/22375607-1869-42a4-885c-b9e22c6898b2)

**Comment by omalk98** [comment]
Fixed with commit #[c065866](https://github.com/omalk98/TILvert/commit/c065866c8a1e5324092d266ed0c89bff85890176)
