### ISSUE TITLE
Adding markdown support (Lab #2)

### ISSUE THREAD

**Issue by sdthaker** [omalk98/TILvert#7]
I'd like to add markdown file processing to this repo, specifically the link feature which'll be parsed to HTML anchor tag whenever a markdown file is passed on the command line as an input.

My idea of implementation is to check whether the file is markdown, by looking at the file extension. If it is a markdown file then use regular expression to match all the links (the content that is wrapped in `()[]`) in a paragraph, and convert them to anchor tags which will then be used as the content to generate paragraph tag. 

All of this will be done in process-file.ts file's processFile function before the segment gets converted to p tag. The reason to do it before the p tag gets assembled is that a link could be part of a p tag so that's why we'd want it to be processed before.

**Comment by omalk98** [comment]
Approved, Please create a pull request and link it to this issue
